version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./my-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: username
      PMA_PASSWORD: password
    ports:
      - 8080:80
    restart: always
    depends_on:
      - mysql

  web:
    build: ./
    container_name: docker-php
    environment:
      DB_HOST: mysql
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql